# Generated by Django 4.1.4 on 2022-12-16 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='amount',
            new_name='message',
        ),
    ]
